In [2]:
import numpy as np

In [4]:
random_arr = np.random.rand(3,3)
print(random_arr)

[[0.09664589 0.961516   0.47744983]
 [0.56073833 0.41010028 0.66519268]
 [0.61800818 0.47673308 0.62230061]]


In [6]:
random_arr = np.random.randint(1,7)
print(random_arr)

2


In [7]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(a[0,2,2])

9


In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print(np.add(a,b,c))
print(np.subtract(b,c,a))
print(np.multiply(b,a,c))

[5 7 9]
[-1 -2 -3]
[ -4 -10 -18]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.min(arr))
print(np.max(arr))
print(arr.T)

matrix = np.array([[1,2], [3,4]])
print(np.linalg.inv(matrix))




3.5
3.5
1.707825127659933
1
6
[[1 4]
 [2 5]
 [3 6]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [29]:
ar = np.array([[1.1,2.2,3.3],[4.4,5.5,6.6],[7.7,8.8,9.9]])
print(np.diag(ar))
print(np.ceil(ar))
print(np.floor(ar))
print(np.sin(ar))
print(np.cos(ar))
print(np.tan(ar))
print(np.square(ar))
print(np.identity(4))

[1.1 5.5 9.9]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 0.89120736  0.8084964  -0.15774569]
 [-0.95160207 -0.70554033  0.31154136]
 [ 0.98816823  0.58491719 -0.45753589]]
[[ 0.45359612 -0.58850112 -0.98747977]
 [-0.30733287  0.70866977  0.95023259]
 [ 0.15337386 -0.81109301 -0.88919115]]
[[ 1.96475966 -1.37382306  0.15974575]
 [ 3.09632378 -0.99558405  0.32785801]
 [ 6.44287247 -0.72114688  0.51455291]]
[[ 1.21  4.84 10.89]
 [19.36 30.25 43.56]
 [59.29 77.44 98.01]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
