In [1]:
# Create a numpy array of numbers from 10 to 50 with step 5
import numpy as np

arr = np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]


In [2]:
# Create a 3x3 matrix with values from 1 to 9
arr = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Reverse a Numpy array
arr = np.array([1,2,3,4,5,6])
print(arr[::-1])

[6 5 4 3 2 1]


In [6]:
# Find indices of non-zero elements in an array
arr = np.nonzero([1,2,0,4,6,0,7,0])
print(arr)

(array([0, 1, 3, 4, 6]),)


In [7]:
# Create an identity matrix of size 4
arr = np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# Find mean. median, and standard deviation of an array.
arr = np.array([12,4,24,53,27,84,21])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

32.142857142857146
24.0
25.463859944346733


In [10]:
# Normalize an array (scales values between 0 and 1)
arr = np.array([10,20,30,40,50,60,70])
normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(normalized)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [11]:
# Multiply two matrices
mata = np.array([[1,2],[3,4]])
matb = np.array([[5,6],[7,8]])
res = np.dot(mata,matb)
print(res)

[[19 22]
 [43 50]]


In [12]:
# Compute dot product of two vectors
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.dot(a,b)
print(c)

32


In [13]:
# Find Unique elements and their counts
arr = np.array([1,2,2,3,3,3,4])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4]
[1 2 3 1]


In [15]:
# Extract elements greater than a given value
arr = np.array([1,2,3,4,5,6,7,8,9])
val = 4
res = arr[arr>val]
print(res)

[5 6 7 8 9]


In [16]:
# Replace all even numbers with -1
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[arr%2==0] = -1
print(arr)

[ 1 -1  3 -1  5 -1  7 -1  9]


In [17]:
# Select elements between two values (10-30)
arr = np.arange(10,31,1)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [18]:
# Find positions where elements match a condition
arr = np.array([1, 5, 3, 8, 2, 7])
pos = np.where(arr > 4)
print(pos)
print(arr[pos])

(array([1, 3, 5]),)
[5 8 7]


In [19]:
# Convert a 1D array into 2D (3X3)
arr = np.array([1,2,3,4,5,6,7,8,9])
res = arr.reshape(3,3)
print(res)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
# Flatten a 2d array
arr = np.array([[1,2,3],[3,4,5]])
flat = arr.flatten()
print(flat)

[1 2 3 3 4 5]


In [23]:
# Stack two arrays vertically and horizontally
a = np.array([1,2,3])
b = np.array([4,5,6])

v = np.vstack((a,b))
h = np.hstack((a,b))

print(v)
print(h)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [24]:
# Find row-wise and column-wise sum of matrix
rr = np.array([[1, 2, 3],
                [4, 5, 6]])

rs = np.sum(arr, axis=1)
cs = np.sum(arr, axis=0)

print(rs)
print(cs)

[ 6 12]
[4 6 8]


In [ ]:
# Sort an Array along a specific axis (say column sorted)
rr = np.array([[1, 2, 3],
                [4, 5, 6]])

colsort = np.sort
